CREATE DATABASE SQL_Practice  --TO CREATE DATABASE

USE SQL_Practice    --- TO SWITCH TO DATABASE


-- TO CREATE TABEL
CREATE TABLE User_Info(
User_iD INT PRIMARY KEY NOT NULL IDENTITY(1,1),
User_Name VARCHAR(25) NOT NULL,
Email VARCHAR(30) NOT NULL,
Password VARCHAR(20) NOT NULL
)

CREATE TABLE UserNotes(
User_iD INT,
Notes VARCHAR(20)
)  


SELECT Notes FROM Notes AS NOTE INNER JOIN User_Info AS UI ON NOTE.User_iD = UI.User_iD 
SELECT User_iD, COUNT(Notes) AS NotesCount FROM UserNotes GROUP BY User_iD

-- ADDING FORGIN KEY User_Info TABLE PRIMAARY KEY ADDED TO Notes Table FORGIN KEY
ALTER TABLE Notes ADD CONSTRAINT FK1 FOREIGN KEY(User_iD) REFERENCES User_Info(User_iD) 

INSERT INTO User_Info VALUES('NANTHA','test@gmail.com','123@abc') 

--USER ID(PRIMARY KEY) VALUE MUST PRESENT IN USER_INFO TABLE ELSE IT SHOWS ERROR
INSERT INTO UserNotes VALUES(2,'Ela notes') 
INSERT INTO UserNotes VALUES(5,'Nantha notes1') 
INSERT INTO UserNotes VALUES(5,'Nantha notes2') 


-- REMOVE TABLE
DROP TABLE Notes 

SELECT * FROM User_Info

SELECT * FROM UserNotes



DELETE FROM User_Info WHERE User_iD = '3'

DELETE FROM Notes WHERE User_iD = '3'


-- TYPE BELOW COMMAND AND EXECUTR IT CREATES STORE PROCEDURE in programmability
USE[SQL_Practice]
GO
CREATE PROCEDURE AddProcedure
AS

